package com.livemart.model;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_RECEIVED,
    NEW_ORDER_RECEIVED,
    ORDER_UPDATE,
    ORDER_CONFIRMED,
    ORDER_PROCESSING,
    ORDER_SHIPPED,
    ORDER_OUT_FOR_DELIVERY,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PRODUCT_LOW_STOCK,
    PAYMENT_RECEIVED,
    DELIVERY_UPDATE,
    GENERAL
}
